FROM nvcr.io/nvidia/pytorch:22.12-py3
ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=UTF-8
RUN mkdir -p /llm-temp && mkdir -p /llama
WORKDIR /llm-temp

RUN apt-get update &&\
    apt-get install -y \
    wget \
    git \
    python3 \
    python3-pip \
    python-is-python3
RUN python -m pip install --upgrade pip wheel
COPY . /llm-temp

ENV NVIDIA_VISIBLE_DEVICES=all
RUN pip install -r requirements.txt && pip install -e .
